version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head && uvicorn coffeetanuki.core.application:app --host 0.0.0.0 --port 5000 --reload'
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: kartoza/postgis:latest
    volumes:
      - postgis_data:/var/lib/postgresql/data
    expose:
      - 5432
    restart: on-failure

volumes:
  postgis_data:
