"""add hours_of_operation column

Revision ID: 018190e3f171
Revises: 325ffc49836d
Create Date: 2023-05-19 01:21:17.125919

"""
from alembic import op
import sqlalchemy as sa
import litestar.contrib.sqlalchemy.types



# revision identifiers, used by Alembic.
revision = '018190e3f171'
down_revision = '325ffc49836d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('hours_of_operation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'hours_of_operation')
    # ### end Alembic commands ###
