"""init tables

Revision ID: 3016f17cf8db
Revises: 
Create Date: 2023-06-21 21:09:38.860703

"""
from alembic import op
import sqlalchemy as sa
import litestar.contrib.sqlalchemy.types

from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision = '3016f17cf8db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('shop',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('coordinates', Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('roaster', sa.String(), nullable=True),
    sa.Column('hours_of_operation', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', litestar.contrib.sqlalchemy.types.GUID(length=16), nullable=False),
    sa.Column('_sentinel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop')),
    sa.UniqueConstraint('name', name=op.f('uq_shop_name'))
    )
    op.create_geospatial_index('idx_shop_coordinates', 'shop', ['coordinates'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('tag',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', litestar.contrib.sqlalchemy.types.GUID(length=16), nullable=False),
    sa.Column('_sentinel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag')),
    sa.UniqueConstraint('name', name=op.f('uq_tag_name'))
    )
    op.create_table('shop_tag',
    sa.Column('shop_id', litestar.contrib.sqlalchemy.types.GUID(length=16), nullable=False),
    sa.Column('tag_id', litestar.contrib.sqlalchemy.types.GUID(length=16), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], name=op.f('fk_shop_tag_shop_id_shop')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_shop_tag_tag_id_tag')),
    sa.PrimaryKeyConstraint('shop_id', 'tag_id', name=op.f('pk_shop_tag'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_tag')
    op.drop_table('tag')
    op.drop_geospatial_index('idx_shop_coordinates', table_name='shop', postgresql_using='gist', column_name='coordinates')
    op.drop_geospatial_table('shop')
    # ### end Alembic commands ###
