"""add roaster column

Revision ID: 325ffc49836d
Revises: c1b095252dc6
Create Date: 2023-05-19 00:59:21.651326

"""
from alembic import op
import sqlalchemy as sa
import litestar.contrib.sqlalchemy.types



# revision identifiers, used by Alembic.
revision = '325ffc49836d'
down_revision = 'c1b095252dc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('roaster', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'roaster')
    # ### end Alembic commands ###
