"""fix sentinel column

Revision ID: 4524ffa36ec1
Revises: ee75c4426a69
Create Date: 2023-07-18 20:27:29.358458

"""
from alembic import op
import sqlalchemy as sa
import litestar.contrib.sqlalchemy.types



# revision identifiers, used by Alembic.
revision = '4524ffa36ec1'
down_revision = 'ee75c4426a69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True))
    op.drop_column('shop', '_sentinel')
    op.add_column('tag', sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True))
    op.drop_column('tag', '_sentinel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('_sentinel', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tag', 'sa_orm_sentinel')
    op.add_column('shop', sa.Column('_sentinel', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('shop', 'sa_orm_sentinel')
    # ### end Alembic commands ###
