"""create amenity and association tables

Revision ID: 455c66d2bba3
Revises: 018190e3f171
Create Date: 2023-05-26 02:52:55.639364

"""
from alembic import op
import sqlalchemy as sa
import litestar.contrib.sqlalchemy.types


# revision identifiers, used by Alembic.
revision = "455c66d2bba3"
down_revision = "018190e3f171"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "amenity",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", litestar.contrib.sqlalchemy.types.GUID(), nullable=False),
        sa.Column("_sentinel", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_amenity")),
    )
    op.create_table(
        "shop_amenity",
        sa.Column("shop_id", litestar.contrib.sqlalchemy.types.GUID(), nullable=True),
        sa.Column(
            "amenity_id", litestar.contrib.sqlalchemy.types.GUID(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["amenity_id"],
            ["amenity.id"],
            name=op.f("fk_shop_amenity_amenity_id_amenity"),
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shop.id"], name=op.f("fk_shop_amenity_shop_id_shop")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shop_amenity")
    op.drop_table("amenity")
    # ### end Alembic commands ###
