"""added description

Revision ID: c03c402eca73
Revises: edac7be62b53
Create Date: 2023-06-09 21:07:21.346270

"""
from alembic import op
import sqlalchemy as sa
import litestar.contrib.sqlalchemy.types



# revision identifiers, used by Alembic.
revision = 'c03c402eca73'
down_revision = 'edac7be62b53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'description')
    # ### end Alembic commands ###
