"""add _sentinel column

Revision ID: c1b095252dc6
Revises: 4040f5ae108a
Create Date: 2023-05-19 00:56:34.050805

"""
from alembic import op
import sqlalchemy as sa
import litestar.contrib.sqlalchemy.types



# revision identifiers, used by Alembic.
revision = 'c1b095252dc6'
down_revision = '4040f5ae108a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('_sentinel', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', '_sentinel')
    # ### end Alembic commands ###
