"""added scope to tags

Revision ID: e001efbbf4da
Revises: 3016f17cf8db
Create Date: 2023-06-21 21:39:43.108327

"""
from alembic import op
import sqlalchemy as sa
import litestar.contrib.sqlalchemy.types



# revision identifiers, used by Alembic.
revision = 'e001efbbf4da'
down_revision = '3016f17cf8db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('scope', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'scope')
    # ### end Alembic commands ###
