"""unique amenity names

Revision ID: edac7be62b53
Revises: 455c66d2bba3
Create Date: 2023-05-29 17:38:14.692747

"""
from alembic import op
import sqlalchemy as sa
import litestar.contrib.sqlalchemy.types



# revision identifiers, used by Alembic.
revision = 'edac7be62b53'
down_revision = '455c66d2bba3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_amenity_name'), 'amenity', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_amenity_name'), 'amenity', type_='unique')
    # ### end Alembic commands ###
